name: sudoku_game_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

#environment:
#  sdk: ">=2.17.1 <3.0.0"
environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.6
  flutter_icons: ^1.1.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
